<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-22T17:21:43 IST" name="Suite" finished-at="2023-06-22T17:22:24 IST" duration-ms="40635">
    <groups>
    </groups>
    <test started-at="2023-06-22T17:21:43 IST" name="Test" finished-at="2023-06-22T17:22:24 IST" duration-ms="40635">
      <class name="com.qa.testCases.TC_LoginTest_01">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.testCases.TC_LoginTest_01@53ce1329]" started-at="2023-06-22T17:21:44 IST" name="setUp" finished-at="2023-06-22T17:21:53 IST" duration-ms="9115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:com.qa.testCases.TC_LoginTest_01@53ce1329]" started-at="2023-06-22T17:21:53 IST" name="loginTest" description="Logging into the banking application with valid credentials" finished-at="2023-06-22T17:21:57 IST" duration-ms="4105" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.pageObjects.LoginPage.verifyUserLoginSuccessfully(LoginPage.java:60)
at com.qa.testCases.TC_LoginTest_01.loginTest(TC_LoginTest_01.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="teaDown()[pri:0, instance:com.qa.testCases.TC_LoginTest_01@53ce1329]" started-at="2023-06-22T17:21:57 IST" name="teaDown" finished-at="2023-06-22T17:21:57 IST" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teaDown -->
      </class> <!-- com.qa.testCases.TC_LoginTest_01 -->
      <class name="com.qa.testCases.TC_CreNewCustomerTest_02">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.testCases.TC_CreNewCustomerTest_02@2c1b194a]" started-at="2023-06-22T17:21:57 IST" name="setUp" finished-at="2023-06-22T17:22:04 IST" duration-ms="6732" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createNewCutomer()[pri:0, instance:com.qa.testCases.TC_CreNewCustomerTest_02@2c1b194a]" started-at="2023-06-22T17:22:04 IST" name="createNewCutomer" description="Adding new Customer and Verifying the newly Added customer" finished-at="2023-06-22T17:22:24 IST" duration-ms="19827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCutomer -->
        <test-method is-config="true" signature="teaDown()[pri:0, instance:com.qa.testCases.TC_CreNewCustomerTest_02@2c1b194a]" started-at="2023-06-22T17:22:24 IST" name="teaDown" finished-at="2023-06-22T17:22:24 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teaDown -->
      </class> <!-- com.qa.testCases.TC_CreNewCustomerTest_02 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
